### ISSUE TITLE
Integrate the project into a continuous integration solution

### ISSUE THREAD

**Issue by hosszubalazs** [dodie/scott#66]
Hey Dávid!

I was wondering if you have plans for integrating the project into a continuous integration system, like Travis CI. Based on the contribution guide, I guess you can include steps like:
- building and testing the core Scott module (mvn clean install). I believe a setup in Travis CI would be very easy to implement: https://docs.travis-ci.com/user/languages/java/
- maybe you can even build and test the Gradle plugin? I'm not yet sure on the project setup. :/ 
- add a static analysis solution, e.g. Sonar or Codacy. I have little experience with Codacy, but integration for open source repos is pretty easy to do. Probably worth a try.

Values I see in this change:
- first and foremost valuable feedback for you after commits, even if you are the only developers.
- helps the contribution flow. If you agree with the toolings, automating static analysis should help speed up the reviews.
- the green badge on the README representing the successful build always looks nice. :) 

Let me know what you think!
Cheers,
Balázs

**Comment by hosszubalazs** [comment]
For a more interesting CI choice maybe consider Azure Pipelines.That is also free for open source projects.
I have no experience with it though, this is the adventure seeking path...

**Comment by dodie** [comment]
Hey @hosszubalazs !

Thanks for the suggestion! I think it's a good idea, it would surely make the life of newcomers easier if they'd get feedback on the PR instantly. This would hopefully result in more contributors, which I'd really appreciate. ;) Static analysis would also be a great addition to PR's.

Building all Scott modules is indeed possible, with one caveat: 
There is a bit of an assymmetry when it comes to the Gradle Plugin module, because it's built with `gradlew`, not `mvn`. So currently, this would require an additional command to be executed. (I think it would be worthwile to remove this quirk, e.g. with a simple pom.xml that makes sure to build this module as part of the Maven lifecycle.)

Cheers,
David

**Comment by dodie** [comment]
I've integrated the project to [Azure pipelines](https://dev.azure.com/dodiehun/scott/_build/results?buildId=18) to build the maven and the gradle based components.

Next, I'll check SonarCloud.

**Comment by dodie** [comment]
Added sonarcloud to the build: 1262f6478b7b05882f8726cbbd5aa1d83dd1014c
Failing PR with some example code smells: #94

**Comment by dodie** [comment]
Thanks for the suggestions @hosszubalazs , now the project has Azure DevOps Pipelines and SonarCloud integration.
